# Generated by Django 4.2.6 on 2023-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
