# Generated by Django 4.2.6 on 2023-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.URLField(default='https://www.pngkey.com/png/detail/233-2332677_ega-png.png'),
        ),
    ]
