# Generated by Django 4.2.4 on 2023-11-23 00:40

from django.db import migrations
import random

def create_bookstock(apps, schema_editor):
    Book = apps.get_model('book', 'Book')
    BookStock = apps.get_model('catalogue', 'BookStock')
    for book in Book.objects.all():
        if not BookStock.objects.filter(book=book).exists():
            BookStock.objects.create(
                book=book,
                quantity=random.randint(100, 500),  # Nilai acak untuk quantity
                price=random.randrange(80000, 1000000, 20000)  # Nilai acak untuk price
            )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_bookstock),
    ]
