# Generated by Django 4.2.4 on 2023-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('image_url_small', models.URLField()),
                ('image_url_medium', models.URLField()),
                ('image_url_large', models.URLField()),
            ],
        ),
    ]
