# Generated by Django 4.2.6 on 2023-10-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user_profile/image/placeholder.jpg', upload_to=''),
        ),
    ]
