# Generated by Django 4.2.6 on 2023-10-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_name_user_user_name_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
