# Generated by Django 4.2.6 on 2023-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_book',
            field=models.JSONField(default=''),
        ),
    ]
