# Generated by Django 4.2.6 on 2023-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_alter_user_favorite_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
